name: .NET Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/prplecake/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx" --results-directory "./TestResults" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Bunny.*.Tests?]*"
      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Test Results
          path: TestResults/*.trx
          reporter: dotnet-trx
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Pack NuGet
        run: dotnet pack src/Bunny.NET/Bunny.NET.csproj -c Release
      - name: Upload NuGet
        run: |
          dotnet nuget push ./src/Bunny.NET/bin/Release/Bunny.NET*.nupkg
